# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hw1020/Documents/FYP_Bayesian_Optimisation/object_functions/NutShell_Prj/NutShell_Prj.srcs/sources_1/bd/nutshell/ip/nutshell_auto_cc_2_2/nutshell_auto_cc_2.xci
# IP: The module: 'nutshell_auto_cc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hw1020/Documents/FYP_Bayesian_Optimisation/object_functions/NutShell_Prj/NutShell_Prj.gen/sources_1/bd/nutshell/ip/nutshell_auto_cc_2_2/nutshell_auto_cc_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'nutshell_auto_cc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hw1020/Documents/FYP_Bayesian_Optimisation/object_functions/NutShell_Prj/NutShell_Prj.gen/sources_1/bd/nutshell/ip/nutshell_auto_cc_2_2/nutshell_auto_cc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nutshell_auto_cc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hw1020/Documents/FYP_Bayesian_Optimisation/object_functions/NutShell_Prj/NutShell_Prj.srcs/sources_1/bd/nutshell/ip/nutshell_auto_cc_2_2/nutshell_auto_cc_2.xci
# IP: The module: 'nutshell_auto_cc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hw1020/Documents/FYP_Bayesian_Optimisation/object_functions/NutShell_Prj/NutShell_Prj.gen/sources_1/bd/nutshell/ip/nutshell_auto_cc_2_2/nutshell_auto_cc_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'nutshell_auto_cc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hw1020/Documents/FYP_Bayesian_Optimisation/object_functions/NutShell_Prj/NutShell_Prj.gen/sources_1/bd/nutshell/ip/nutshell_auto_cc_2_2/nutshell_auto_cc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nutshell_auto_cc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
